--- 
title: "R for Bioinformatics"
author: "颤抖吧小虫子"
date: "`r Sys.Date()`"
documentclass: ctexbook
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
geometry: [b5paper, tmargin=2.5cm, bmargin=2.5cm, lmargin=3.5cm, rmargin=2.5cm]
site: bookdown::bookdown_site
description: "一个简单的中文书示例。"
github-repo: yihui/bookdown-chinese
cover-image: images/cover.npg
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# 填上你需要用到的包，如 c('ggplot2', 'dplyr')
lapply(c(), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

# 前言 {-}

你好，最近萌生了想写一本书的念头，以目前自己的能力还是主要参考网上众多博客和教程，感谢他们的无私奉献。第 \@ref(intro) 章介绍了啥啥，第\@ref(wind) 章说了啥啥，然后是啥啥……

这本书的框架主要参考[谢益辉大神](https://yihui.org/)的**bookdown**\index{bookdown} [@R-bookdown]。以下是我的 R 进程信息：

```{r}
sessionInfo()
```

## 致谢 {-}

感谢所有帮助我的人。

```{block2, type='flushright', html.tag='p'}
颤抖吧小虫子
于中科院奥运村科技园动物所A座
```

